nohup: ignoring input
2021-07-17 13:34:05.930873: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: :/home/micrl/.mujoco/mjpro150/bin:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64:/home/micrl/.mujoco/mjpro150/bin:/usr/local/cuda-10.1/lib64:/usr/local/cuda-10.0/lib64
2021-07-17 13:34:05.930900: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11111] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11113] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11115] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11117] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11119] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11121] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11123] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11125] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@100] [$11127] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:23.817 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@100] [$32871] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@100] [$32873] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@100] [$32875] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.844 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@100] [$33405] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@100] [$33407] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@100] [$33409] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:27.845 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85167] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85169] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85171] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 93, in collide
    dist = self.sdf(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 59, in sdf
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85701] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85703] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@100] [$85705] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.651 13428] [type_check.cpp:visit@101] 
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 198, in grid_op
    v_out = self.primitives[i].collide(f, I * self.dx, v_out, self.dt)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 96, in collide
    D = self.normal(f, grid_pos)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 50, in decorated
    return fun.__call__(*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 122, in __call__
    ret = self.compiled(*args)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 79, in normal
    grid_pos = inv_trans(grid_pos, self.position[f], self.rotation[f])
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/util.py", line 163, in wrapped
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/impl.py", line 201, in maybe_transform_ti_func_call_to_stmt
    return func(*args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/common_ops.py", line 227, in assign
    return ti.assign(self, other)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/ops.py", line 130, in wrapped
    return a.element_wise_writeback_binary(imp_foo, b)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/matrix.py", line 179, in element_wise_writeback_binary
    ret.entries[i] = foo(self.entries[i], other.entries[i])

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$89319] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$89337] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$89463] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$89487] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$89575] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.963 13428] [type_check.cpp:visit@100] [$90346] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@100] [$90371] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@100] [$90458] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@100] [$90812] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@100] [$90827] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@100] [$90842] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:34:49.964 13428] [type_check.cpp:visit@101] 

[W 07/17/21 13:35:03.108 13428] [type_check.cpp:visit@100] [$131560] Local store may lose precision (target = f32, value = f64) at
[W 07/17/21 13:35:03.108 13428] [type_check.cpp:visit@101] 

[E 07/17/21 14:07:21.451 13428] [cuda_driver.h:operator()@81] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling memcpy_host_to_device (cuMemcpyHtoD_v2)


[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDADriverFunction<void*, void*, unsigned long>::operator()(void*, void*, unsigned long)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CodeGenLLVMCUDA::compile_module_to_executable()::{lambda(taichi::lang::Context&)#1}::operator()(taichi::lang::Context&) const
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Kernel::operator()(taichi::lang::Kernel::LaunchContextBuilder&)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x35b04a) [0x7f1878d6b04a]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x34476a) [0x7f1878d5476a]
[0m[38;2;255;000;255mpython(PyCFunction_Call+0x54) [0x560ce42cc834]
[0m[38;2;255;000;255mpython(_PyObject_MakeTpCall+0x158) [0x560ce428dda8]
[0m[38;2;255;000;255mpython(+0x1a3747) [0x560ce42c5747]
[0m[38;2;255;000;255mpython(PyVectorcall_Call+0x6e) [0x560ce428eede]
[0m[38;2;255;000;255mpython(+0xb8557) [0x560ce41da557]
[0m[38;2;255;000;255mpython(_PyObject_MakeTpCall+0x158) [0x560ce428dda8]
[0m[38;2;255;000;255mpython(_PyEval_EvalFrameDefault+0x3c3) [0x560ce42e8673]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x952) [0x560ce42ba132]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x19b) [0x560ce42ba7fb]
[0m[38;2;255;000;255mpython(PyVectorcall_Call+0x6e) [0x560ce428eede]
[0m[38;2;255;000;255mpython(_PyEval_EvalFrameDefault+0x4e70) [0x560ce42ed120]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x1e9) [0x560ce42b99c9]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x19b) [0x560ce42ba7fb]
[0m[38;2;255;000;255mpython(_PyObject_FastCallDict+0xd2) [0x560ce42a5242]
[0m[38;2;255;000;255mpython(_PyObject_Call_Prepend+0x67) [0x560ce4312a27]
[0m[38;2;255;000;255mpython(+0x1f0aa8) [0x560ce4312aa8]
[0m[38;2;255;000;255mpython(PyObject_Call+0x61) [0x560ce428f061]
[0m[38;2;255;000;255mpython(_PyEval_EvalFrameDefault+0x4e70) [0x560ce42ed120]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x1e9) [0x560ce42b99c9]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x19b) [0x560ce42ba7fb]
[0m[38;2;255;000;255mpython(_PyObject_FastCallDict+0x56) [0x560ce42a51c6]
[0m[38;2;255;000;255mpython(_PyObject_Call_Prepend+0x67) [0x560ce4312a27]
[0m[38;2;255;000;255mpython(+0x1f0aa8) [0x560ce4312aa8]
[0m[38;2;255;000;255mpython(_PyObject_MakeTpCall+0x158) [0x560ce428dda8]
[0m[38;2;255;000;255mpython(_PyEval_EvalFrameDefault+0x4448) [0x560ce42ec6f8]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x108) [0x560ce42ba768]
[0m[38;2;255;000;255mpython(PyVectorcall_Call+0x6e) [0x560ce428eede]
[0m[38;2;255;000;255mpython(_PyEval_EvalFrameDefault+0x4e70) [0x560ce42ed120]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x952) [0x560ce42ba132]
[0m[38;2;255;000;255mpython(+0x1a345b) [0x560ce42c545b]
[0m[38;2;255;000;255mpython(+0x146149) [0x560ce4268149]
[0m[38;2;255;000;255mpython(+0x1a3376) [0x560ce42c5376]
[0m[38;2;255;000;255mpython(+0x146149) [0x560ce4268149]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x108) [0x560ce42ba768]
[0m[38;2;255;000;255mpython(+0x146254) [0x560ce4268254]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x886) [0x560ce42ba066]
[0m[38;2;255;000;255mpython(+0x1a34c6) [0x560ce42c54c6]
[0m[38;2;255;000;255mpython(+0x145cc7) [0x560ce4267cc7]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x1e9) [0x560ce42b99c9]
[0m[38;2;255;000;255mpython(+0x1a34c6) [0x560ce42c54c6]
[0m[38;2;255;000;255mpython(+0x146149) [0x560ce4268149]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x952) [0x560ce42ba132]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x19b) [0x560ce42ba7fb]
[0m[38;2;255;000;255mpython(+0x145e14) [0x560ce4267e14]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x952) [0x560ce42ba132]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x19b) [0x560ce42ba7fb]
[0m[38;2;255;000;255mpython(+0x146254) [0x560ce4268254]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x108) [0x560ce42ba768]
[0m[38;2;255;000;255mpython(+0x145e14) [0x560ce4267e14]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x108) [0x560ce42ba768]
[0m[38;2;255;000;255mpython(+0x145e14) [0x560ce4267e14]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x1e9) [0x560ce42b99c9]
[0m[38;2;255;000;255mpython(+0x1e1e8f) [0x560ce4303e8f]
[0m[38;2;255;000;255mpython(+0x16f61d) [0x560ce429161d]
[0m[38;2;255;000;255mpython(+0x145e14) [0x560ce4267e14]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x886) [0x560ce42ba066]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x1ff) [0x560ce42ba85f]
[0m[38;2;255;000;255mpython(+0x145e14) [0x560ce4267e14]
[0m[38;2;255;000;255mpython(_PyEval_EvalCodeWithName+0x1e9) [0x560ce42b99c9]
[0m[38;2;255;000;255mpython(_PyFunction_Vectorcall+0x1ff) [0x560ce42ba85f]
[0m[38;2;255;000;255mpython(PyVectorcall_Call+0x6e) [0x560ce428eede]
[0m[38;2;255;000;255mpython(+0x207fca) [0x560ce4329fca]
[0m[38;2;255;000;255mpython(Py_RunMain+0x13c) [0x560ce432b84c]
[0m[38;2;255;000;255mpython(Py_BytesMain+0x39) [0x560ce432bca9]
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
[0m[38;2;255;000;255mpython(+0x1e21c7) [0x560ce43041c7]
[0m[38;2;255;165;000m
Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/gym/logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
Traceback (most recent call last):
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/micrl/chensirui/PlasticineLab/plb/algorithms/solve.py", line 91, in <module>
    main()
  File "/home/micrl/chensirui/PlasticineLab/plb/algorithms/solve.py", line 86, in main
    learn_latent(env, args.path, args)
  File "/home/micrl/chensirui/PlasticineLab/plb/optimizer/learn_latent.py", line 139, in learn_latent
    current_loss = solver.solve(state,action,target,grad_buffer,state_buffer)
  File "/home/micrl/chensirui/PlasticineLab/plb/optimizer/learn_latent.py", line 56, in solve
    loss, (x_hat_grad,v_hat_grad) = forward(state_hat,target,action)
  File "/home/micrl/chensirui/PlasticineLab/plb/optimizer/learn_latent.py", line 38, in forward
    env.step(action[0])
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/taichi_env.py", line 82, in step
    self.simulator.step(is_copy=self._is_copy, action=action)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/mpm_simulator.py", line 391, in step
    self.primitives.set_action(start//self.substeps, self.substeps, action)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primitives.py", line 293, in set_action
    self.primitives[i].set_action(s, n_substeps, action[self.action_dims[i]:self.action_dims[i+1]])
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 207, in set_action
    self.no_grad_set_action_kernel(s, action) #HACK: taichi can't compute gradient to this.
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/__init__.py", line 853, in decorated
    func(*args, **kwargs)
  File "/home/micrl/chensirui/PlasticineLab/plb/engine/primitive/primive_base.py", line 173, in no_grad_set_action_kernel
    self.set_action_kernel(s, action)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 668, in __call__
    return self._primal(self._kernel_owner, *args, **kwargs)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 563, in __call__
    return self.compiled_functions[key](*args)
  File "/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/lang/kernel_impl.py", line 517, in func__
    t_kernel(launch_ctx)
RuntimeError: [cuda_driver.h:operator()@81] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling memcpy_host_to_device (cuMemcpyHtoD_v2)
[Taichi] mode=release
[Taichi] preparing sandbox at /tmp/taichi-aqh8vmlc
[Taichi] version 0.7.23, llvm 10.0.0, commit 0b89df86, linux, python 3.8.10
Loaded compiled 3D CUDA chamfer distance
[Taichi] Starting on arch=cuda
Building primitive
action:
  dim: 7
  scale: (0.02, 0.02, 0.02, 0.04, 0.04, 0.04, 0.02)
color: (0.8, 0.8, 0.8)
friction: 10.0
h: 0.2
init_gap: 0.06
init_pos: (0.5, 0.15, 0.5)
init_rot: (1.0, 0.0, 0.0, 0.0)
lower_bound: (0.0, 0.0, 0.0)
minimal_gap: 0.06
r: 0.02
shape: Chopsticks
upper_bound: (1.0, 1.0, 1.0)
variations: None
{'width': (0.04, 0.04, 0.6), 'init_pos': (0.5, 0.02, 0.5), 'color': 100, 'n_particles': 8192}
Number of particles:  8192
Initialize Renderer
bake_size: 6  
camera_pos: (0.5, 1.2, 4.0)  
camera_rot: (0.2, 0)  
dx: 0.006666666666666667  
image_res: (512, 512)  
light_direction: (2.0, 1.0, 0.7)  
max_num_particles: 1000000  
max_ray_depth: 2  
sdf_threshold: 0.20720000000000002  
spp: 50  
target_res: (64, 64, 64)  
use_directional_light: True  
use_roulette: False  
voxel_res: (168, 168, 168)
[Taichi] materializing...
TaichiEnv Number of Particles: 8192
Batch: 1 Loss:  0.03829057347029448
Batch: 2 Loss:  0.035827115084975956
Batch: 3 Loss:  0.03752374919131398
Batch: 4 Loss:  0.031725041847676036
Batch: 5 Loss:  0.037257829774171115
Batch: 6 Loss:  0.03254606015980244
Batch: 7 Loss:  0.035048161167651415
Batch: 8 Loss:  0.034759920183569194
Batch: 9 Loss:  0.03358721313998103
Batch: 10 Loss:  0.03283485891297459
Batch: 11 Loss:  0.03505067825317383
Batch: 12 Loss:  0.032886752486228944
Batch: 13 Loss:  0.04085147241130471
Batch: 14 Loss:  0.03295338563621044
Batch: 15 Loss:  0.0315266971476376
Batch: 16 Loss:  0.0327782460488379
Batch: 17 Loss:  0.032701145950704814
Batch: 18 Loss:  0.03447716645896435
Batch: 19 Loss:  0.03316308129578829
Batch: 20 Loss:  0.03191128363832831
Batch: 21 Loss:  0.032371741533279416
Batch: 22 Loss:  0.034046274796128276
Batch: 23 Loss:  0.03505142042413354
Batch: 24 Loss:  0.032474919501692054
Batch: 25 Loss:  0.0318374564871192
Batch: 26 Loss:  0.032307086512446404
Batch: 27 Loss:  0.03252735380083323
Batch: 28 Loss:  0.03405246678739786
Batch: 29 Loss:  0.03488072380423546
Batch: 30 Loss:  0.03513853810727596
Batch: 31 Loss:  0.03590886862948537
Batch: 32 Loss:  0.03363656075671315
Batch: 33 Loss:  0.03505440941080451
Batch: 34 Loss:  0.03219650909304619
Batch: 35 Loss:  0.034359501022845504
Batch: 36 Loss:  0.03520175414159894
Batch: 37 Loss:  0.03306012563407421
Batch: 38 Loss:  0.03219598643481732
Batch: 39 Loss:  0.036821522004902366
Batch: 40 Loss:  0.03310656165704131
Batch: 41 Loss:  0.036692310590296984
Batch: 42 Loss:  0.032004352752119304
Batch: 43 Loss:  0.03517123395577073
Batch: 44 Loss:  0.03553052982315421
Batch: 45 Loss:  0.03194664502516389
Batch: 46 Loss:  0.036422149278223515
Batch: 47 Loss:  0.035452908091247085
Batch: 48 Loss:  0.032584029249846935
Batch: 49 Loss:  0.03374459752812982
Loss:  0.03145914524793625
Batch: 50 Loss:  0.03102497197687626
Batch: 51 Loss:  0.035743300709873436
Batch: 52 Loss:  0.035602590534836054
Batch: 53 Loss:  0.03650409616529941
Batch: 54 Loss:  0.0312843726016581
Batch: 55 Loss:  0.03751412890851498
Batch: 56 Loss:  0.032152526546269655
Batch: 57 Loss:  0.034987487737089394
Batch: 58 Loss:  0.034507932420819995
Batch: 59 Loss:  0.03306734897196293
Batch: 60 Loss:  0.0326090476475656
Batch: 61 Loss:  0.03490302674472332
Batch: 62 Loss:  0.032510279677808285
Batch: 63 Loss:  0.040351448114961386
Batch: 64 Loss:  0.03264026707038283
Batch: 65 Loss:  0.031141478195786478
Batch: 66 Loss:  0.0324527527205646
Batch: 67 Loss:  0.032447356078773734
[E 07/17/21 14:07:21.727 13428] [cuda_driver.h:operator()@81] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling stream_synchronize (cuStreamSynchronize)


[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDADriverFunction<void*>::operator()(void*)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x59b777) [0x7f1878fab777]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::finalize()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::~Program()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x3e346e) [0x7f1878df346e]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x34a8db) [0x7f1878d5a8db]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x34a5ec) [0x7f1878d5a5ec]
[0m[38;2;255;000;255mpython(+0x15893b) [0x560ce427a93b]
[0m[38;2;255;000;255mpython(+0x15bdf5) [0x560ce427ddf5]
[0m[38;2;255;000;255mpython(+0x1670f2) [0x560ce42890f2]
[0m[38;2;255;000;255mpython(_PyGC_CollectNoFail+0x2a) [0x560ce431c64a]
[0m[38;2;255;000;255mpython(PyImport_Cleanup+0x3b5) [0x560ce42f7dc5]
[0m[38;2;255;000;255mpython(Py_FinalizeEx+0x79) [0x560ce4329a49]
[0m[38;2;255;000;255mpython(Py_RunMain+0x183) [0x560ce432b893]
[0m[38;2;255;000;255mpython(Py_BytesMain+0x39) [0x560ce432bca9]
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
[0m[38;2;255;000;255mpython(+0x1e21c7) [0x560ce43041c7]
[0m[38;2;255;165;000m
Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0m[E 07/17/21 14:07:21.760 13428] [cuda_driver.h:operator()@81] CUDA Error CUDA_ERROR_ILLEGAL_ADDRESS: an illegal memory access was encountered while calling mem_free (cuMemFree_v2)
terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'


[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::CUDADriverFunction<void*>::operator()(void*)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::UnifiedAllocator::~UnifiedAllocator()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::MemoryPool::~MemoryPool()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x5b2f97) [0x7f1878fc2f97]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::lang::Program::~Program()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x3e346e) [0x7f1878df346e]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x34a8db) [0x7f1878d5a8db]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x34a5ec) [0x7f1878d5a5ec]
[0m[38;2;255;000;255mpython(+0x15893b) [0x560ce427a93b]
[0m[38;2;255;000;255mpython(+0x15bdf5) [0x560ce427ddf5]
[0m[38;2;255;000;255mpython(+0x1670f2) [0x560ce42890f2]
[0m[38;2;255;000;255mpython(_PyGC_CollectNoFail+0x2a) [0x560ce431c64a]
[0m[38;2;255;000;255mpython(PyImport_Cleanup+0x3b5) [0x560ce42f7dc5]
[0m[38;2;255;000;255mpython(Py_FinalizeEx+0x79) [0x560ce4329a49]
[0m[38;2;255;000;255mpython(Py_RunMain+0x183) [0x560ce432b893]
[0m[38;2;255;000;255mpython(Py_BytesMain+0x39) [0x560ce432bca9]
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6: __libc_start_main
[0m[38;2;255;000;255mpython(+0x1e21c7) [0x560ce43041c7]
[0m[38;2;255;165;000m
Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0m[E 07/17/21 14:07:21.764 13428] Received signal 6 (Aborted)


[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m* Taichi Compiler Stack Traceback *
[0m[38;2;255;000;255m***********************************
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so: taichi::Logger::error(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x5e78b4) [0x7f1878ff78b4]
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6(+0x3f040) [0x7f1923bb0040]
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6: gsignal
[0m[38;2;255;000;255m/lib/x86_64-linux-gnu/libc.so.6: abort
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/bin/../lib/libstdc++.so.6: __gnu_cxx::__verbose_terminate_handler()
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/bin/../lib/libstdc++.so.6(+0xacf6f) [0x7f191eef6f6f]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/bin/../lib/libstdc++.so.6(+0xacfb1) [0x7f191eef6fb1]
[0m[38;2;255;000;255m/home/micrl/anaconda2/envs/taichi/lib/python3.8/site-packages/taichi/core/../lib/taichi_core.so(+0x33976b) [0x7f1878d4976b]
[0m[38;2;255;165;000m
Internal error occurred. Check out this page for possible solutions:
https://taichi.readthedocs.io/en/stable/install.html#troubleshooting
[0m